function YL_Doc(){var _CONFIG={}
_CONFIG.class={"title":"yld-title","page":"yld-page","def-header":"yld-def-header","header":"yld-page-header","def-footer":"yld-def-footer","footer":"yld-page-footer","pagenbr":"yld-pagenbr","page-summary":"yld-page-summary","summary":"yld-summary","summary-entry":"yld-summary-entry","img-legend":"yld-img-legend","bibliography":"yld-bibliography","imageography":"yld-imageography"};_CONFIG.settings={"title-nbr":true,"page-nbr":true,"page-outof":true,"page-outof-symbole":" of ","auto-refresh":false,"auto-interval":2000};_CONFIG.counters={"img":0,"a":0,};_CONFIG.summary={"nbrtitle":45};this.init=function(){headerFooter();if(_CONFIG.settings["auto-refresh"]){setInterval("location.reload(true)",_CONFIG.settings["auto-interval"]);}};var imgLegends=function(){$("img").each(function(){var title=$(this).attr("title");var ref=$(this).attr("ref");if(title){_CONFIG.counters["img"]++;$(this).after("<div class='"+_CONFIG.class["img-legend"]+"'>"+title+" <sup>"+_CONFIG.counters["img"]+"</sup></div>");$("."+_CONFIG.class["imageography"]).append("<div>["+_CONFIG.counters["img"]+"] "+title+" <i>("+ref+"</i>)</div>");}});};var aRef=function(){$("a").each(function(){_CONFIG.counters["a"]++;var link=$(this).attr("href");var text=$(this).text();var ref=$(this).attr("ref");var show=text;if(ref!==undefined){show=ref+"("+text+")";}
$(this).append(" <sup>["+_CONFIG.counters["a"]+"]</sup>");$("."+_CONFIG.class["bibliography"]).append("<div>"+"<span class='index'>["+_CONFIG.counters["a"]+"] </span>"+"<span class='text'>"+show+": "+"<span class='link'><a href='"+link+"'>"+link+"</a></div>");});};var _getHeader=function(){return"<div class="+_CONFIG.class["header"]+">"+
$("."+_CONFIG.class["def-header"]).html()+"</div>"}
var _getFooter=function(){return $("."+_CONFIG.class["def-footer"]).html()}
var headerFooter=function(){$("."+_CONFIG.class["page"]).each(function(i,page){var pagenbr=i+1;$(page).prepend(_getHeader());$(page).append("<div class="+_CONFIG.class["footer"]+">"+_getFooter()+"</div>");var outof="";if(_CONFIG.settings["page-outof"]){outof=_CONFIG.settings["page-outof-symbole"]+$(".yld-page").length;}
if(_CONFIG.settings["page-nbr"]){$(page).find("."+_CONFIG.class["footer"]).append("<div class="+_CONFIG.class["pagenbr"]+">Page "+pagenbr+outof+"</div>");$(page).find("."+_CONFIG.class["pagenbr"]).addClass('col g2');}});};var createSummary=function(){var JSP_TITLE_NBR=0;var JSP_TITLE2_NBR=0;var JSP_TITLE3_NBR=0;var JSP_TITLE4_NBR=0;var pagenbr=0;var nbrtitle=0;$("."+_CONFIG.class["page"]).each(function(i,page){pagenbr++;$(page).find("."+_CONFIG.class["title"]).each(function(_,title){var t=$(title).text();var tag=$(this)[0].tagName;var h_nbr="";nbrtitle++;if(tag==="H1"){JSP_TITLE_NBR++;JSP_TITLE2_NBR=0;h_nbr=JSP_TITLE_NBR;}
if(tag==="H2"){JSP_TITLE2_NBR++;JSP_TITLE3_NBR=0;h_nbr=JSP_TITLE_NBR+"."+JSP_TITLE2_NBR;}
if(tag==="H3"){JSP_TITLE3_NBR++;JSP_TITLE4_NBR=0;h_nbr=JSP_TITLE_NBR+"."+JSP_TITLE2_NBR+"."+JSP_TITLE3_NBR;}
if(tag==="H4"){JSP_TITLE4_NBR++;h_nbr=JSP_TITLE_NBR+"."+JSP_TITLE2_NBR+"."+JSP_TITLE3_NBR+"."+JSP_TITLE4_NBR;}
if(_CONFIG.settings["page-nbr"]){$(title).text(h_nbr+" "+t);}
if(nbrtitle%_CONFIG.summary["nbrtitle"]==0){$("."+_CONFIG.class["page-summary"]).last().after("</div><div class='"+
_CONFIG.class["page-summary"]+" "+
_CONFIG.class["page"]+"'><div class='"+_CONFIG.class["summary"]+"'></div>");$("."+_CONFIG.class["page-summary"]).last().prepend(_getHeader());}
$("."+_CONFIG.class["summary"]).last().append("<div class='"+_CONFIG.class["summary"]+"-"+tag+" "+
_CONFIG.class["summary-entry"]+"'>"+h_nbr+" "+t+"<div>"+pagenbr+"</div></div>");});});};var adaptPage=function(){$("."+JSP_PAGE_CLASS).each(function(i,page){var totalH=0;var pages=[$(this)];var page_elements=[];var tmp_content=[];$(this).children().each(function(){var elH=$(this).outerHeight();if((totalH+elH)<JSP_PAGE_PIXEL){tmp_content.push($(this));totalH+=elH;}
else{page_elements.push(tmp_content);tmp_content=[$(this)];totalH=elH;var new_page=createPage("?");pages[pages.length-1].after(new_page);pages.push(new_page);}});page_elements.push(tmp_content);for(var i=0;i<page_elements.length;i++){pages[i].text("").append(page_elements[i]);}});};}
var doc=new YL_Doc();doc.init();